{
 "title": "Infinispan",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(vendor_cache_manager_default_number_of_cache_configurations,namespace)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(vendor_cache_manager_default_number_of_cache_configurations{namespace=~\"$namespace\"}, service)"
   },
   {
    "name": "caches",
    "query": "query_result({job=~\"$cluster\", namespace=~\"$namespace\", __name__=~\"vendor_cache_manager_default_cache_.*_cluster_cache_stats_activations\"})"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Replicas (up)",
   "type": "singlestat",
   "description": "The number of pods in the cluster",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$cluster-[0-9]+\"}) by (namespace) # kube specific, need OS?",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Readiness Probes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Ready" }
   ],
   "targets": [
    {
     "expr": "sum(up{namespace=~\"$namespace\", job=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(up{namespace=~\"$namespace\", job=~\"infinispan-operator.*\"}) by (pod) # TODO - what does the operator expose?",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Off-Heap",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(base_memory_usedNonHeap_bytes{namespace=~\"$namespace\", job=~\"$cluster\"})*100/sum(base_memory_maxNonHeap_bytes{namespace=~\"$namespace\", job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{namespace=~\"$namespace\", job=~\"$cluster\"})*100/sum(base_memory_maxHeap_bytes{namespace=~\"$namespace\", job=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\", pod=~\"$cluster-[0-9]+\"})\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"memory\", pod=~\"$cluster-[0-9]+\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "container_memory_rss{namespace=~\"$namespace\", container=\"infinispan\", pod=~\"$cluster-[0-9]+\"}",
     "legendFormat": "RSS for {{pod}}"
    },
    {
     "expr": "base_memory_committedHeap_bytes{namespace=~\"$namespace\", job=~\"$cluster\"}",
     "legendFormat": "JVM Committed for {{pod}}"
    },
    {
     "expr": "base_memory_maxHeap_bytes{namespace=~\"$namespace\", job=~\"$cluster\"}",
     "legendFormat": "JVM Max for {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{namespace=~\"$namespace\", job=~\"$cluster\"}",
     "legendFormat": "CPU Usage {{pod}}"
    }
   ]
  },
  {
   "title": "Number of GC Collections [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(base_gc_total{namespace=~\"$namespace\", job=~\"$cluster\"}[30m])) by (pod)",
     "legendFormat": "GC Collections for {{pod}}"
    }
   ]
  },
  {
   "title": "IO Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{namespace=~\"$namespace\",job=~\"$cluster\"}",
     "legendFormat": "Threads {{pod}}"
    },
    {
     "expr": "base_thread_daemon_count{namespace=~\"$namespace\",job=~\"$cluster\"}",
     "legendFormat": "Deamon Threads  {{pod}}"
    },
    {
     "expr": "base_thread_max_count{namespace=~\"$namespace\",job=~\"$cluster\"}",
     "legendFormat": "Max Threads {{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "JVM Heap {{pod}}"
    },
    {
     "expr": "sum(base_memory_usedNonHeap_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "JVM Non Heap {{pod}}"
    }
   ]
  },
  {
   "title": "Total GC Time [30m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(base_gc_time_total_seconds{namespace=~\"$namespace\", job=~\"$cluster\"}[30m])) by (pod)",
     "legendFormat": "Total GC Time for {{pod}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$caches",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "repeat": "caches",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_number_of_entries\"})",
     "legendFormat": "Entries"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_current_number_of_entries_in_memory\"})",
     "legendFormat": "Entries In-Memory"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_hits\"})",
     "legendFormat": "Hits"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_misses\"})",
     "legendFormat": "Misses"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_remove_hits\"})",
     "legendFormat": "Remove Hits"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_remove_misses\"})",
     "legendFormat": "Remove Misses"
    }
   ]
  },
  {
   "title": "$caches Latencies",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "repeat": "caches",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_average_write_time\"})",
     "legendFormat": "Writes"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_average_read_time\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_average_remove_time\"})",
     "legendFormat": "Remove"
    }
   ]
  },
  {
   "title": "$caches",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_number_of_entries\"})",
     "legendFormat": "Entries"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_current_number_of_entries_in_memory\"})",
     "legendFormat": "Entries In-Memory"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_hits\"})",
     "legendFormat": "Hits"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_misses\"})",
     "legendFormat": "Misses"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_remove_hits\"})",
     "legendFormat": "Remove Hits"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_remove_misses\"})",
     "legendFormat": "Remove Misses"
    }
   ]
  },
  {
   "title": "$caches Latencies",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_average_write_time\"})",
     "legendFormat": "Writes"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_average_read_time\"})",
     "legendFormat": "Reads"
    },
    {
     "expr": "max({namespace=~\"$namespace\", job=~\"$cluster\", __name__=~\"vendor_cache_manager_default_cache_($caches)_cluster_cache_stats_average_remove_time\"})",
     "legendFormat": "Remove"
    }
   ]
  }
 ]
}